### ISSUE TITLE
Using with Oauth credentials

### ISSUE THREAD

**Issue by Hhavoc** [iprak/winix#11]
I quickly realized my google name/password were invalid in the app, because I've been using the Google Oauth login option. Any way to incorporate this, or is creating a new separate Winix account required?

**Comment by anna328p** [comment]
I created/moved to a new winix account. Not sure if it's possible to use oauth credentials.

**Comment by iprak** [comment]
You would want to create an account without oauth; there is no support for this in the underlying library.
