### ISSUE TITLE
Locale issue

### ISSUE THREAD

**Issue by int-rnd** [iprak/winix#13]
The locale of the runpsace must have 'en_US.utf8' installed and configured otherwise the custom component will fail on line 97 in init when it goes to log in. The error will be "unsupported locale setting" when the custom component is initialized. To check what is installed, run locale -a within the runspace where the custom component runs.

While it would probably be best to not require a fixed locale, I was able to get the winix custom component to work by adding 'en_US.utf8' by uncommenting it from /etc/locale.gen and then running sudo locale-gen and restarting the homeassistant.

Hope this helps and provides enough detail for both a fix/workaround. 

For reference, many stripped down runspaces only support few locales:
C
C.UTF-8
POSIX

**Comment by iprak** [comment]
How are you running HomeAssistant? What error were you seeing?

**Comment by iprak** [comment]
This component itself does not require any fixed locale but it is based on https://github.com/hfern/winix which uses `binascii` and probably has an indirect requirement. I think you have the Home Assistant Supervised installation and manually installing the missing piece is the best solution which I can think of. I will not be able to anything in this regards.
