### ISSUE TITLE
Missing turbo speed

### ISSUE THREAD

**Issue by kreene1987** [iprak/winix#18]
First off thanks for the integration. Works excellent along with the air purifier card in lovelace.

My C545's are missing the speed "turbo":
```
speed_list:
  - 'off'
  - low
  - medium
  - high
  - Auto
  - Manual
  - Manual+Plasma
  - Sleep
preset_modes:
  - Auto
  - Manual
  - Manual+Plasma
  - Sleep
speed: Auto
percentage: null
percentage_step: 25
preset_mode: Auto
mode: auto
airflow: low
aqi: 1
plasma: 'on'
filter_hour: 1856
air_quality: good
air_qvalue: 170
ambient_light: 212
location: OLTH2
filter_replace_date: '2021-06-20 18:30:02.0'
friendly_name: Winix Bedroom
supported_features: 9
```

Also should Auto, Manual, Manual+Plasma, and Sleep be in both the speed list and the preset_modes list?

**Comment by iprak** [comment]
Resolved in v0.7

**Comment by ponchohoncho** [comment]
@kreene1987 can you share your YAML for the air purifier card? I can't seem to set the speeds using mine, it keeps saying things like "Failed to call service fan/set_speed. The speed turbo is not a valid speed."

**Comment by ponchohoncho** [comment]
aha, so it's the card at https://github.com/denysdovhan/purifier-card that needs to be updated to use the new service? Is that something that @denysdovhan could look at?

What does the mapping between the list of speeds in this entity and the percentage speed that we set with fan.set_percentage?

**Comment by iprak** [comment]
The mapping is done in Winix component using helpers provided by homeassistant.

The implementation is as per https://developers.home-assistant.io/docs/core/entity/fan#deprecated-properties

The card invokes set `fan.set_speed` service and calling that manually from Developer tab gave this warning: `WARNING (MainThread) [homeassistant.components.fan] The fan.set_speed service is deprecated, use fan.set_percentage or fan.set_preset_mode instead`.

I just use the native Entity card for controlling the purifier
![image](https://user-images.githubusercontent.com/6459774/129119969-ab76e8a6-5335-4386-95fd-f3352dabad7e.png)
