### ISSUE TITLE
UserNotFoundException

### ISSUE THREAD

**Issue by git2021-ll** [iprak/winix#24]
On 2021.9.2 pushed the latest version but I'm receiving an error when attempting to load the component. "An error occurred (UserNotFoundException) when calling the InitiateAuth operation: User does not exist. " Account works as expected logging into smart app; anything I can do to troubleshoot?

**Comment by iprak** [comment]
The exception seems to be originating from boto3 package which is AWS SDK, it gets used indirectly winix > hfern/winix > warrant_lite > boto3. 

Google Search gave some [hits](https://www.google.com/search?q=InitiateAuth+%2B%22User+does+not+exist%22&sxsrf=AOaemvInDW1u93xjLgDoL2uPND5QszWsyw%3A1630841052326&ei=3Kg0YbWgE865-wSw85KIDA&oq=InitiateAuth+%2B%22User+does+not+exist%22&gs_lcp=Cgdnd3Mtd2l6EAM6BwgAEEcQsANKBAhBGABQvgVYvgVg4QZoAHADeACAAVmIAVmSAQExmAEAoAEByAEIwAEB&sclient=gws-wiz&ved=0ahUKEwi1_u6s3OfyAhXO3J4KHbC5BMEQ4dUDCA8&uact=5) but I am not sure what is causing that exception in your case in this context,

**Comment by git2021-ll** [comment]
Just a few questions for you:
Don't need to escape special characters in the username (e-mail address
contains a period, etc) in the YAML, etc?

Only account needed is the one from in the Winix Smart App yea?


Thanks,

LL

**Comment by iprak** [comment]
No the email/password don't need to be escaped. 

That error should appear if the email is not the registered; I defined this in my settings and got that error.

```wininx_email: someone@gmail.com```

**Comment by iprak** [comment]
My testing is consistently showing that this was due to incorrect username (email id).

**Comment by git2021-ll** [comment]
Indu,

Appreciate the follow-up. I think the issue might have been me using the
Google SSO initially. Even though I created an account and could manually
log in, deleting my account and starting over allowed the custom component
to connect.


Thanks!

LL
