### ISSUE TITLE
Action Icons Invisible?

### ISSUE THREAD

**Issue by jeanofthedead** [iprak/winix#27]
I'm not sure what I did, but suddenly the action bar icons are gone. [Here's what I mean](https://imgur.com/a/4Xlj6d6). Any ideas why? I'm running HA Core 2021.11.1.

**Comment by jeanofthedead** [comment]
Here's my configuration:

`type: custom:purifier-card
entity: fan.winix_living_room
aqi:
  attribute: air_quality
  unit: AQI
show_name: true
show_state: true
show_toolbar: true
compact_view: false
actions:
  - name: Plasma
    icon: mdi:lightning-bolt
    service: winix.plasmawave_toggle
  - name: Low
    icon: mdi:circle-slice-2
    service: fan.set_percentage
    service_data:
      percentage: 25
  - name: Medium
    icon: mdi:circle-slice-4
    service: fan.set_percentage
    service_data:
      percentage: 50
  - name: High
    icon: mdi:circle-slice-6
    service: fan.set_percentage
    service_data:
      percentage: 75
  - name: Turbo
    icon: mdi:circle-slice-8
    service: fan.set_percentage
    service_data:
      percentage: 100
`

**Comment by iprak** [comment]
Sorry I don't know what could be causing this. I did not note any breaking changes in this regards in [2021.11.1](https://www.home-assistant.io/blog/2021/11/03/release-202111/).

Anyway, this is repo is not for purifier-card, you should log the issue in its [repo](https://github.com/denysdovhan/purifier-card/issues).
