### ISSUE TITLE
HR1000 light switch

### ISSUE THREAD

**Issue by albertogarciacz** [iprak/winix#31]
Hi, at first thank you for your amazing work. This component works really nice for me. However, I am a owner of HR1000 and even though everything works as it should there is no service for control of its lights. So I thought such an extension would be interesting for me and other HR1000 owners.

**Comment by iprak** [comment]
The integration is based on the good work done Hunter (https://github.com/hfern/winix). The underlying driver and this were both originally intended only for C545. Later it was reported that functional aspects of HR1000 work and so it was added. Sorry, I cannot do anything more unless there support is exposed in the underlying driver. Also I don't have that model so can't tinker with it.
