### ISSUE TITLE
Integrate Air Quality Sensor?

### ISSUE THREAD

**Issue by jeanofthedead** [iprak/winix#32]
I was wondering if there was a way to expose the air quality sensor to HomeKit from this HA integration?

I am currently exposing fan.winix_living_room and sensor.winix_living_room to HomeKit, but I don't see an air quality sensor like I did when I used Homebridge (only the fan/speed/Plasmawave/preset entities).

**Comment by iprak** [comment]
Winix only gives 2 values: `Air qValue` and `Air quality`. Based on the data I have seen, this is not the same as [AQI index](https://www.airnow.gov/aqi/aqi-basics/). I seen values like qValue=75, quality=good. There is no documentation of the values or any value corresponding to the standard air quality metrics.

**Comment by jeanofthedead** [comment]
Gotcha. Yeah, it looks like the Homebridge Winix plugin uses the following scheme:

```

getAirQuality: function (callback) {
        if (!this.device) {
            callback(new Error('No Air Purifier is discovered.'));
            return;
        }

        this.getStatusFromServer(this.serverStatuses.AIR_QUALITY)
            .then((status) => {
                let quality = Characteristic.AirQuality.UNKNOWN;

                if (status === 1) {
                    quality = Characteristic.AirQuality.GOOD
                }
                if (status === 2) {
                    quality = Characteristic.AirQuality.FAIR
                }
                if (status === 3) {
                    quality = Characteristic.AirQuality.POOR
                }

                return quality;
            })
            .then((quality) => {
                callback(null, quality)
            });
    },
```

Would it be possible to use the same scheme when exposing your integration to HomeKit? I'm not too savvy, but it looks so good in the Home.app, haha.

**Comment by iprak** [comment]
Sorry I don't think I can do that. There is no air quality metric with good/fair/poor values. The AirQualitySensor [has been deprecated](https://developers.home-assistant.io/docs/core/entity/air-quality/) and float value based sensors need to be used.

**Comment by jeanofthedead** [comment]
No worries. Thanks for all your work!
