### ISSUE TITLE
Startup problem

### ISSUE THREAD

**Issue by pmele** [iprak/winix#33]
Downloaded the winix directory and placed in my /config/custom_components/ and restarted.

Added login info into my configuration.yaml and restarted.

Does not show any of the c545 units in my home.

Using the following on Linux deb using virtualBox
Home Assistant 2022.2.9
Home Assistant OS 7.4
supervisor-2022.01.1

What did I miss?  When I used Docker and Supervisor it worked right away.  Thanks!

**Comment by iprak** [comment]
I would enable debug logging to see what might be happening. I suspect that authentication might be failing.

```
logger:
  default: debug
```

**Comment by iprak** [comment]
Any data on this?

**Comment by pmele** [comment]
Quite honestly I do not remember this.  I have since crashed and rebuilt HA and everything has been working fine.
