### ISSUE TITLE
Think I'm seeing the issue

### ISSUE THREAD

**Issue by Jeppedy** [iprak/winix#37]
Setting this up for the first time, and I'm getting:
Error parsing response json, received {'statusCode': 200, 'headers': {'resultCode': 'S100', 'resultMessage': 'no data'}, 'body': {}}

I noticed a continuing issue mentioned:  One of the units on the account was inaccessible
I had two devices configured on my account, one which is not currently on-line.  I removed the device that was not connected, there were  no more log errors and the entities appeared.

**Comment by Jeppedy** [comment]
Confirmed.  The problem is with inaccessible units.  Looks like insufficient error handling when querying status for the units.  If you can't communicate with the unit, the process just dies.

**Comment by iprak** [comment]
Hello, do you remember any more details about this? I unplugged one of my devices and Winix server continue to report it as `off`. The message mentioned above was in a try/catch and I am improving that to prevent the callers from crashing if that happens.

**Comment by iprak** [comment]
I just pushed out a new `breaking` release which should handle such a situation in better manner.

**Comment by iprak** [comment]
I think this issue has been resolved. If you still run into it, then let me know and I will reopen this.
