### ISSUE TITLE
Question: Winix smart app and this component

### ISSUE THREAD

**Issue by scadaguru** [iprak/winix#40]
Thank you so much for the good work! Appreciate it!

Can we use both this custom component and Winix Smart app both?
It seems app gets logged out saying you logged somewhere else and if I login to app again on phone I believe this component never updates value in Home Assistant.
Anyone seeing similar behavior?
Thanks

**Comment by iprak** [comment]
So I am not seeing that behavior any more. I am actually logged in the webApp and still see updates coming to 2 HomeAssistant instances. I was able to start/stop purifiers from both the app and HomeAssistant. It seems that I never log off my phone app. I will keep looking into this.

**Comment by scadaguru** [comment]
Thanks for the update.
Yes, app on phone did ask once but after that both seems working as expected.
