### ISSUE TITLE
Import into HomeKit as Air Purifier device type?

### ISSUE THREAD

**Issue by jeanofthedead** [iprak/winix#42]
Hi, with Homebridge, I am able to import my Winix C545 into Home.app as an 'Air Purifier' with an air quality sensor. I don't see Air Purifier listed as a device type in the HA Homekit core integration, but I know it's a support device type in Home.app. Is there a way to do this manually?

As far as the air quality sensor part goes, it looks like the Homebridge dev assigned arbitrary values to the Winix's 'good, etc.' values. It looks really nice having this sensor in Home.app, though, and I was wondering if this could be added as well?

Thanks for all your hard work!

**Comment by iprak** [comment]
The integration has a Device entry if the integration was added via Config Flow which doesn't happen to be the case for Winix, so all one gets are Entities. As far as I know, the Device cannot be manually created.

**Comment by jeanofthedead** [comment]
Understood. Thanks.

**Comment by iprak** [comment]
I just pushed out a new `breaking` release which supports config flow and should help with your setup.
