### ISSUE TITLE
Winix Tower XQ Light

### ISSUE THREAD

**Issue by stephenjamieson** [iprak/winix#46]
Hello!  I saw the AQI levels were implemented as a sensor and I was wondering if the corresponding light on the Tower XQ could be managed?  Unfortunately it turns back on if I turn off the unit.  Let me know if you need any information.

**Comment by iprak** [comment]
Sorry this integration has only been verified on C545 and AM90. Some of the existing APIs might work with Tower but there is no controllable lights on C545.

**Comment by stephenjamieson** [comment]
Ok thanks.  Seems like they all overlap, so I'd be happy to investigate further if you'd point me in the right direction.  Either way thanks for the integration.

**Comment by iprak** [comment]
That will be nice. The integration is basically based on reverse engineering calls from Winix mobile app. There is no documentation about the APIs. It internally uses modified https://github.com/hfern/winix which seems to be written on the same pattern. You can parse the apk using online tools.
