### ISSUE TITLE
Possible to expose as air purifier in HomeKit?

### ISSUE THREAD

**Issue by jeanofthedead** [iprak/winix#50]
Hi, I was wondering if it was possible to expose this device as an air purifier instead of a fan in the native HomeKit integration? The [Homebridge plugin](https://github.com/banzalik/homebridge-winix-c545) is somehow able to do this.

I appreciate your work!

**Comment by iprak** [comment]
I am not seeing any [Air Purifier component](https://www.home-assistant.io/integrations/) in HomeAssistant. I looked at a few existing Xiami Air Purifiers and they too seem to appear as fan entities. That plugins interact with HomeBridge itself and so that might be feasible there.

**Comment by jeanofthedead** [comment]
Interesting. Yes, I suppose there must be a classification when the entities are being shared with HomeKit. Here's what it looks like after added to HomeKit from the Homebridge: air purifier, air quality sensor, and PlasmaWave switch. ![image](https://user-images.githubusercontent.com/56093335/229205544-aa755894-dec5-4045-b428-796d2c9ff0ed.jpeg)

**Comment by jeanofthedead** [comment]
It looks like there's a request to bring the air purifier entity type to be the HomeKit integration for HA [here](https://github.com/ak6i/core/tree/homekit_air_purifier). Some folks are [trying to get the air purifier type into HomeKit](https://community.home-assistant.io/t/support-air-purifier-device-type-in-homekit/154078), but it seems to require that the fan entity also has a matching PM2.5 entity. Does the Winix plugin that you made also offer an exposed PM2.5 entity, or just the AQI and proprietary Winix air quality value? I wonder if there was a way to call the AQI value PM2.5 instead?

**Comment by iprak** [comment]
Sorry, C545 does not provide any PM data.  AQI cannot be used as PM2.5.

This was the response in this regards from Winix support

```
Your unit utilizes a smart sensor to monitor any odors that may arise in the room. This sensor then communicates with the Winix Smart App to provide a read out throughout the day.

Good (Blue) = 1
Fair (Amber) = 2
Poor (Red) = 3
```
