### ISSUE TITLE
Have C545; not seeing choices about plasmawave or fan speed

### ISSUE THREAD

**Issue by theschles** [iprak/winix#56]
Hi there,

Home Assistant 2023.7.3 Frontend 20230705.1 - latest  (installed as docker container)
HACS Integration version: | 1.32.1
Frontend version: | 20220906112053

I just installed the Winix integration via HACS -- and then added the integration via Home Assistant's Devices section

I do get the four main entities:

<img width="767" alt="image" src="https://github.com/iprak/winix/assets/901430/1d9ca106-8ee7-461b-bed2-b0fae8458eab">

And the files which are supposed to be `<config directory>/custom_components/winix/` are there:

```
<config_directory>/custom_components/winix $ ls -la
total 92
drwxr-xr-x 4 root root 4096 Aug 13 14:17 .
drwxr-xr-x 7 root root 4096 Aug 13 11:39 ..
-rw-r--r-- 1 root root 4146 Aug 13 11:39 config_flow.py
-rw-r--r-- 1 root root 2483 Aug 13 11:39 const.py
-rw-r--r-- 1 root root 8151 Aug 13 11:39 device_wrapper.py
-rw-r--r-- 1 root root 7025 Aug 13 11:39 driver.py
-rw-r--r-- 1 root root 8046 Aug 13 11:39 fan.py
-rw-r--r-- 1 root root 7744 Aug 13 11:39 helpers.py
-rw-r--r-- 1 root root 4912 Aug 13 11:39 __init__.py
-rw-r--r-- 1 root root 3603 Aug 13 11:39 manager.py
-rw-r--r-- 1 root root  332 Aug 13 11:39 manifest.json
drwxr-xr-x 2 root root 4096 Aug 13 14:18 __pycache__
-rw-r--r-- 1 root root 4232 Aug 13 11:39 sensor.py
-rw-r--r-- 1 root root  757 Aug 13 11:39 services.yaml
-rw-r--r-- 1 root root  591 Aug 13 11:39 strings.json
drwxr-xr-x 2 root root 4096 Aug 13 11:39 translations
```

So why don't I see:
* `winix.plasmawave_off`
* `winix.plasmawave_on
* `plasmawave_toggle`
* `fan.speed`
* `fan.set_preset_mode`
???

**Comment by iprak** [comment]
Those should appear under services like this
![image](https://github.com/iprak/winix/assets/6459774/1248c6ea-4bcb-46d9-9f4b-d0e2658c024c)

**Comment by theschles** [comment]
Ah there they are!

Would someone please post instructions how to add the services to a card so I can choose them like in the screenshot on the `README.md`?

**Comment by iprak** [comment]
These are some links which I found on google; I think the first one is simplest.

assistant.io/integrations/input_button/#:~:text=The%20preferred%20way%20to%20configure,next%20choose%20the%20Button%20option.

https://github.com/custom-cards/button-card

https://community.home-assistant.io/t/call-service-button-from-lovelace/168656
https://www.home-

**Comment by theschles** [comment]
Had to mess around a bit but I got it working...
