### ISSUE TITLE
Is it posible to set the ambient_light setting via an automation?

### ISSUE THREAD

**Issue by ziptbm** [iprak/winix#57]
Just purchased a Winix and installed this package...working well, however it took me some time to realize that just because the preset_mode was in "sleep" didn't mean that it wasn't in "auto" mode.  Please correct me if I'm not understanding this correctly.

This isn't an issue, but rather a question - is it possible to set the ambient_light attribute through a service call of some sort?  I've noticed this go up and down and would like it as low as it can go at night if possible.  Thanks!

**Comment by iprak** [comment]
Sorry, the ambient light cannot be set from the mobile App which is what the underlying library is based on.
