### ISSUE TITLE
Confirmed working with Costco Winix Air Purifiers

### ISSUE THREAD

**Issue by sirabdude** [iprak/winix#58]
Just installed in my Home Assistant and can confirm this integration is compatible with the Winix purifiers sold at Costco: [model c909](https://www.costco.com/winix-c909-4-stage-air-purifier-with-wi-fi-%2526-plasmawave-technology.product.100842491.html)

**Comment by iprak** [comment]
Than you for confirming that. I have added it to the Readme.
