### ISSUE TITLE
Deprecation of all magic numbers for supported features

### ISSUE THREAD

**Issue by wshuman3** [iprak/winix#62]
As of Home Assistant Core 2024.1, all usage of magic numbers for supported features is deprecated, and each entity platform has provided an EntityFeature enum to replace them.

There will be a one-year deprecation period, and the magic numbers will stop working in 2025.1 to ensure all custom integration authors have time to adjust.

```
Entity None (<class 'custom_components.winix.fan.WinixPurifier'>) is using deprecated supported features values which will be removed in HA Core 2025.1. Instead it should use <FanEntityFeature.SET_SPEED|PRESET_MODE: 9>, please create a bug report at https://github.com/iprak/winix/issues and reference https://developers.home-assistant.io/blog/2023/12/28/support-feature-magic-numbers-deprecation
```

**Comment by wshuman3** [comment]
See https://developers.home-assistant.io/blog/2023/12/28/support-feature-magic-numbers-deprecation/ for more information.

**Comment by iprak** [comment]
What version of integration are you using?

**Comment by wshuman3** [comment]
I was on 1.1.4, didn't see it addressed in the release, but I see it in this [commit](https://github.com/iprak/winix/commit/fcbb6570a722c356135b548caaecf21e08d07a46).  Sorry for the noise.

**Comment by iprak** [comment]
No problem. That was just some code cleanup, I don't think this was a warning at that point.
