### ISSUE TITLE
Can't add integration to 2024.3.3

### ISSUE THREAD

**Issue by nforceroh** [iprak/winix#64]
I followed the instructions but when after I enter my login info for winix I get
Logger: homeassistant.setup
Source: setup.py:266
First occurred: 4:44:54 PM (1 occurrences)
Last logged: 4:44:54 PM

Setup failed for custom integration 'winix': No setup or config entry setup function defined.

**Comment by iprak** [comment]
What is the integration version?

**Comment by nforceroh** [comment]
I had done a git clone initially but since you asked the version, I tried to download the 1.1.5 zip of the release, installed it and that worked. sorry!
