### ISSUE TITLE
Light sensor

### ISSUE THREAD

**Issue by carlocardella** [iprak/winix#66]
Thanks for the plugin, I installed it just recently but it works well so far. 

Is it possible to expose the light sensor to Home Assistant? I would like to use it to trigger automations when the light level crosses a certain threshold. 

Thanks

**Comment by iprak** [comment]
The `ambient_light` property indicates ambient light.
You can create a template sensor based on that property and then trigger your automation, there is an example on HomeAssistant wki about `Attributes of the entity`.

https://www.home-assistant.io/docs/automation/trigger/

**Comment by carlocardella** [comment]
I do not see it (hence the question), I only have these four

![image](https://github.com/iprak/winix/assets/5784415/24f000fc-dc90-4a3d-966a-88335833748d)

**Comment by iprak** [comment]
That is an attribute on the sensor and not a sensor itself. You can see it under "Developer Tools > STATES" where you can search your Winix entity sensor.

**Comment by carlocardella** [comment]
Found it, thanks
