### ISSUE TITLE
Deleting Winix Air Purifiers

### ISSUE THREAD

**Issue by marshalltech81** [iprak/winix#67]
I recently upgraded 5 of my air purifiers.  However with the integration there was no way to delete the old air purifiers and add the new ones without removing the integration and adding it back.  Is there an easier way to do this?

Also do you have a "Buy Me a Coffee"?

**Comment by iprak** [comment]
Sorry, you will have to remove+add the integration to make that happen. I can look into this but it will take some time. I will also add "Buy me a Coffee" button something. Thanks.

**Comment by iprak** [comment]
Deleted purifiers entries can be manually deleted using a new service introduced in v1.1.6.
