### ISSUE TITLE
Qvalue appears in history as a bar chart rather than a line graph

### ISSUE THREAD

**Issue by ChrisMD123** [iprak/winix#8]
First, thanks for building this - it's awesome!

One minor request (I don't know enough about how to write these to change it myself): it would be great if the integer values like qvalue would appear as continuous integers (and thus would appear in History as a line graph rather than a bar chart):

![image](https://user-images.githubusercontent.com/4922831/103379943-3b966e00-4a9c-11eb-9343-96d883819948.png)

From what I've read, this would require adding a unit_of_measurement to the definition of the template/value.

**Comment by iprak** [comment]
I realized this earlier but could not come up with a unit which explains what QValue is. Well it is something related to air quality value. I am planning to just use "QV" as the unit.

**Comment by ChrisMD123** [comment]
Sounds good to me! Thanks again.

**Comment by ChrisMD123** [comment]
Awesome, thanks!
![image](https://user-images.githubusercontent.com/4922831/103425293-4584a380-4b66-11eb-8dc1-b68b6d7215ba.png)
