### ISSUE TITLE
Winix air purifier does not show air quality

### ISSUE THREAD

**Issue by Trinita2020** [iprak/winix#88]
Air quality shows unknown

**Comment by iprak** [comment]
Which sensor are you referring to .. "Air QValue" or "AQI" ? Can you provide a screenshot of the device page?

**Comment by morozgrafix** [comment]
I'm troubleshooting my Winix Integration at the moment. Saw this in the logs:

```Logger: custom_components.winix.driver
Source: custom_components/winix/driver.py:193
integration: Winix Air Purifier ([documentation](https://github.com/iprak/winix), [issues](https://github.com/iprak/winix/issues))
First occurred: 7:34:17 PM (78 occurrences)
Last logged: 7:53:25 PM

Error parsing response json, received {'statusCode': 200, 'headers': {'resultCode': 'S100', 'resultMessage': 'no data'}, 'body': {}}
Traceback (most recent call last):
  File "/config/custom_components/winix/driver.py", line 193, in get_state
    payload = json["body"]["data"][0]["attributes"]
              ~~~~~~~~~~~~^^^^^^^^
KeyError: 'data'```

**Comment by iprak** [comment]
That's just Winix not supplying the data. We can't do much about it. The message is coming from the error trap.

**Comment by morozgrafix** [comment]
Yes I agree. Not sure what was causing it, but I ended up disabling and then enabling the integration and it started to pick up info from both of my C545 units. I didn't get a chance to grab a screenshot, but it was showing `Unknown` for `AirQ Value`, `AQI` and `Filter life`

**Comment by iprak** [comment]
I have seen this data behavior and it usually resolves itself in a few minutes. Also Winix end point also _sometimes_ complains  if one has logged into the mobile app at the same time.

I have not seen any special handling for missing data in other integrations so I am tempted to put any extra logic to maintain previous value. But this becomes a repetition then something like that can be included. If the login credentials have expired then a different error is logged.

**Comment by Trinita2020** [comment]
Hi all
Filter life is working. It is really the air quality that does show as unknown. I have 4 times redone the integration. It always shows aa unknown

**Comment by iprak** [comment]
That is possible. 

T800 was reported to be working (https://github.com/iprak/winix/issues/86) but I cannot personally confirm that. You can enable debug logging to see what data is being returned for T800.

Go to `Settings > Integrations`, Winix and then `Enable debug logging`.

I would also add that this integration relies on [winix library](https://github.com/hfern/winix) and so T800 might not completely work unless that supports it.

**Comment by Trinita2020** [comment]
Thanks a lot for all these great insights. However, the debugging does not provide any data given the air quality is unknown. This is super unfortunate as this would be the key for so many automations to start and stop

**Comment by iprak** [comment]
> Thanks a lot for all these great insights. However, the debugging does not provide any data given the air quality is unknown. This is super unfortunate as this would be the key for so many automations to start and stop

What is the sensor you are looking at? "Air QValue" or "AQI" ?
Also would you mind adding the debug response content for reference?

**Comment by Trinita2020** [comment]
I am extremely sorry to ask you how to pull that data as I have run the debug mode now for a couple of days and I cannot find a way to extract the data. Please help me on that.

**Comment by iprak** [comment]
> I am extremely sorry to ask you how to pull that data as I have run the debug mode now for a couple of days and I cannot find a way to extract the data. Please help me on that.

No need to be sorry. If you go to `Settings > System > Logs` and then `Show raw logs` from the ... then you should see data like

`2024-12-29 19:40:03.035 DEBUG (MainThread) [custom_components.winix.driver] {'statusCode': 200, 'headers': ...`

**Comment by Trinita2020** [comment]
It is really frustrating that there is no entry. Even I used the non working air quality as a base and let it run. If you wish I can even send you a video if you give me clear instructions. But, I would not like to publish this video widely due to security concerns.

**Comment by iprak** [comment]
> It is really frustrating that there is no entry. Even I used the non working air quality as a base and let it run. If you wish I can even send you a video if you give me clear instructions. But, I would not like to publish this video widely due to security concerns.

Do you see any messages for `custom_components.winix.helpers` or  `custom_components.winix.manager` ?

**Comment by morozgrafix** [comment]
@Trinita2020 In order to save your debug logs to your computer. In your browser get to the page of the Winix integration via HA settings and click on `Enable Debug Logging`, let it log for some time and then when you click on `Disable Debug Logging` HA should prompt you to save a log file (or possibly just automatically download the log file to your downloads directory).
![image](https://github.com/user-attachments/assets/31d09a0a-06ca-49dc-bfa9-e6d38b25208c)

**Comment by Trinita2020** [comment]
Of course, I have done thar. i have even created an automation that triggers the air quality. However, given the air quality is unknown, no log is created. If you wish I can even send you a video showing it

**Comment by Trinita2020** [comment]
The Development tool under Statistic provides as fix issue option to delete sensor.winix.air.purifier.filter.life and ...aqi

**Comment by Trinita2020** [comment]
![image](https://github.com/user-attachments/assets/248476e0-d110-4774-9763-abad2bd4e39c)

**Comment by Trinita2020** [comment]
This doesn't help at all I guess

**Comment by iprak** [comment]
Can you add a screenshot of the entities showing for your integration? You can access them from the entities link here.
![image](https://github.com/user-attachments/assets/38b4a22e-6d95-4dcd-a92a-c8be449a37ad)

**Comment by Trinita2020** [comment]
![image](https://github.com/user-attachments/assets/fc545852-cf52-484d-9741-0ef2fd78db4b)

**Comment by Trinita2020** [comment]
![image](https://github.com/user-attachments/assets/ac29b75e-7ed1-4d63-b5a3-1de899b8a44a)

**Comment by Trinita2020** [comment]
Sure. I appreciate your continuous support on that matter. This is the newest version of winix so I really struggle why it would not work properly

**Comment by iprak** [comment]
The entity count looks okay. Which entity are you trying to use? Does the filter life sensor have valid value?

**Comment by Trinita2020** [comment]
![image](https://github.com/user-attachments/assets/eec1db99-8a19-40da-aede-e422cfd68a06)

**Comment by Trinita2020** [comment]
This one. This is a major sensor for any subsequent automations

**Comment by Trinita2020** [comment]
The filter live I can oversee. Ao no major issue

**Comment by iprak** [comment]
But are you seeing valid filter value?

**Comment by iprak** [comment]
You mentioned that Developer Tools gives an option to delete the statistics. Did you already do that?

**Comment by Trinita2020** [comment]
It says unknown. And in developer tool I have not deleted it as I do not know what it does to the integration

**Comment by Trinita2020** [comment]
![image](https://github.com/user-attachments/assets/6bb621e7-cdad-4522-b4b9-37c53ee8a932)

**Comment by Trinita2020** [comment]
Maybe this helps

**Comment by iprak** [comment]
I would say at this point you can go ahead the delete the values from STATISTICS. We can always delete the integration and add it back as well. Usually the delete option appears if nothing is updating that entity.

**Comment by Trinita2020** [comment]
But that cannot be the solution. Common

**Comment by Trinita2020** [comment]
Any news? I have entities that don't provide correct data. I want to use these data for automations. Deleting it... doesn't solve the problem. Apologize for being persistent

**Comment by iprak** [comment]
I don't have anything new to add. I have yet to see any debug log. The integration primarily support C545. I cannot say what the behavior is for T800.

**Comment by Trinita2020** [comment]
I made a couple of screenshots. In my view this doesn't say anything. However, I am not an expert like you. This is with debug mode![image](https://github.com/user-attachments/assets/daa796cf-85b3-4e50-89f0-9faf0e992af0)![image](https://github.com/user-attachments/assets/cfe8c242-a0dc-49b8-a3bb-310e701fc427)![image](https://github.com/user-attachments/assets/b03b60dc-b451-4d0c-a16a-79efdef260a2)![image](https://github.com/user-attachments/assets/5740d420-8d87-4f70-bfae-3676770365a6)

**Comment by Trinita2020** [comment]
I have created a script that should activate winix if airq is abirre 10. i have sent all logs that i can find wrt winix. I truly hope this helps

**Comment by iprak** [comment]
That screenshot of the data received was helpful. Turns out T800 does not support or provide data for air_quality/air_qvalue. The data markers for those are S07 and S08 which are absent. It could be that data is provided in some other format. 

This integration is intended for C545 and with Winix clones which operate like C545. T800 does not seem to fall in that category. T800 was added to readme because it was reported to be functional (https://github.com/iprak/winix/issues/86). I will clarify that air quality is not supported.

**Comment by Trinita2020** [comment]
Do you believe that this item will be added anytime soon? T800 was advertised as a flagship. I truly hope this will be fixed soon

**Comment by iprak** [comment]
Further investigation would a physical device. I don't intend to acquire one. I also believe this model is not sold in US. I am closing this issue, the readme has been adjusted.

**Comment by Trinita2020** [comment]
Would you be interested to help me this going?

**Comment by Trinita2020** [comment]
I would appreciate your help getting this this integration successful. Let me know what you expect to get this sorted out
Sent from my iPhone

On 12 Jan 2025, at 16:42, Indu Prakash ***@***.***> wrote:

﻿
CAUTION: This email originated from outside of Alcon. Always verify the sending address and use caution when opening links or opening attachments unless you recognize the sender and know the content is safe.
____________________________________


Further investigation would a physical device. I don't intend to acquire one. I also believe this model is not sold in US. I am closing this issue, the readme has been adjusted.
